apiVersion: v1
kind: Service
metadata:
  name: energy-service
  namespace: irrigation
spec:
  selector:
    app: energy-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-service
  namespace: irrigation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: energy-service
  template:
    metadata:
      labels:
        app: energy-service
    spec:
      containers:
        - name: energy-service
          image: irrigation-microservices-energy-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            # Doit matcher spring.application.name=MSEnergy
            - name: SPRING_APPLICATION_NAME
              value: MSEnergy
            - name: SERVER_PORT
              value: "8081"

            # Même URL que dans MSEnergy.properties
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/energy_db?serverTimezone=UTC&createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

            # RabbitMQ identique au properties
            - name: SPRING_RABBITMQ_ADDRESSES
              value: "amqps://nyfiwlit:mOidKOQPt8C9unLjDQgxE3BwuEv3gnbZ@campbell.lmq.cloudamqp.com/nyfiwlit"

            # Eureka : même host que dans MSEnergy.properties + Service K8s
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

##          livenessProbe:
##            httpGet:
##              path: /actuator/health
##              port: 8081
##            initialDelaySeconds: 30
##            periodSeconds: 10

##          readinessProbe:
##            httpGet:
##              path: /actuator/health
##              port: 8081
##            initialDelaySeconds: 20
##            periodSeconds: 5