apiVersion: v1
kind: Service
metadata:
  name: water-service
  namespace: irrigation
spec:
  selector:
    app: water-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: water-service
  namespace: irrigation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: water-service
  template:
    metadata:
      labels:
        app: water-service
    spec:
      containers:
        - name: water-service
          image: irrigation-microservices-water-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            # Optionnel, Spring peut lire MSWater.properties depuis Config Server
            - name: SPRING_APPLICATION_NAME
              value: MSWater
            - name: SERVER_PORT
              value: "8082"

            # Si tu veux override la datasource par env (même valeur que MSWater.properties)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/water_db?serverTimezone=UTC&createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

            # RabbitMQ (même que dans MSWater.properties)
            - name: SPRING_RABBITMQ_ADDRESSES
              value: "amqps://nyfiwlit:mOidKOQPt8C9unLjDQgxE3BwuEv3gnbZ@campbell.lmq.cloudamqp.com/nyfiwlit"

            # Eureka : garder le même host que dans MSWater.properties et que ton Service K8s
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

 ##         livenessProbe:
 ##           httpGet:
 ##             path: /actuator/health
 ##             port: 8082
 ##           initialDelaySeconds: 30
 ##           periodSeconds: 10

##          readinessProbe:
##            httpGet:
##              path: /actuator/health
##              port: 8082
##            initialDelaySeconds: 20
##            periodSeconds: 5